import AppContextProvider from '@/context/AppContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body className='dark:bg-navy-900'>
        <AppContextProvider>
        {children}
        </AppContextProvider>
        </body>
    </html>
  )
}
